name: Build
on: [workflow_dispatch]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: "Sample circuits"
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Setup requirements
        run: pip install -r requirements.txt

      - name: Generate page
        run: python -m gospel.scripts.generate_page

      - name: Publish pages
        run: rsync -avz pages/ /www/
