name: CI

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "Sample circuits"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Setup requirements
        run: pip install -r requirements.txt

      - name: Run experiment
        run: cd sampling_circuits && python experiments.py

      - name: Archive distribution
        uses: actions/upload-artifact@v4
        with:
          name: distribution
          path: sampling_circuits/circuits/distribution.svg
